/**
 * Operations & Financial Report — server-computed, printable.
 * Renders GET /api/reports/overview: the backend calculates every total,
 * gender split and breakdown from the authoritative tables. The printed
 * document is self-contained (Report ID, period, filters, generated-by,
 * position, timestamp) so it is understandable without ERP access.
 */
import { text } from '../../design-system/styles';
import React, { useEffect, useState, useCallback } from 'react';
import { Printer, RefreshCw, Users, UserPlus, GraduationCap, FileText, BookOpen, Wallet, TrendingUp, TrendingDown } from 'lucide-react';
import { api } from '../../api/client';
import { useDatasetVersion } from '../../state/serverStateFreshness';
import type { OperationsReport } from '../../types';
import { formatAFN } from '../../utils/format';
import { formatJalaliDateTime } from '../../utils/jalali';
import { ShamsiDateInput } from '../common/ShamsiDateInput';
import { BRAND_NAME, brandPrintHeaderHtml } from '../../config/branding';
import { openPrintDocument } from '../../design-system/print';

type Period = 'today' | 'month' | 'year' | 'range';
type Gender = 'all' | 'male' | 'female';

const inputCls = 'border border-slate-200 rounded-lg px-3 py-2 bg-white font-semibold text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500/30 focus:border-indigo-400 transition-all cursor-pointer text-xs';

function printableReport(report: OperationsReport) {
  const m = report.meta;
  const f = m.filters;
  const money = (n: number) => n.toLocaleString('en-US') + ' AFN';
  const rows = (list: { category: string; total: number }[]) => list.map((r) =>
    `<tr><td class="cat">${r.category.replace(/_/g, ' ')}</td><td class="num">${money(r.total)}</td></tr>`).join('');
  const bodyHtml = `
    ${brandPrintHeaderHtml()}
    <div class="title">Operations &amp; Financial Report — ${m.periodLabel}</div>
    <div class="meta">
      Report ID: <b>${m.reportId}</b><br>
      Type: <b>${m.type}</b> · Period: <b>${m.from} → ${m.to}</b> · Scope: <b>${f.scope}</b>${f.branchName ? ` · Branch: <b>${f.branchName}</b>` : ''}${f.campusName ? ` · Campus: <b>${f.campusName}</b>` : ''} · Gender: <b>${f.gender}</b><br>
      Generated by: <b>${m.generatedBy.name}</b> · Position: <b>${m.position}</b> · Timestamp: <b>${formatJalaliDateTime(m.generatedAt)}</b>
    </div>
    <h2>Financial summary</h2>
    <div class="grid">
      <div>Income (operating)<div class="kpi" style="color:#047857">${money(report.financial.income.total)}</div></div>
      <div>Expenses (operating)<div class="kpi" style="color:#be123c">${money(report.financial.expense.total)}</div></div>
      <div>Net<div class="kpi" style="color:${report.financial.net >= 0 ? '#047857' : '#be123c'}">${money(report.financial.net)}</div></div>
      <div>Collected payments<div class="kpi">${report.financial.collectedPayments.count} (${money(report.financial.collectedPayments.total)})</div></div>
    </div>
    <h2>Income by category</h2>
    <table>${rows(report.financial.income.byCategory)}<tr class="total"><td>Total</td><td class="num">${money(report.financial.income.total)}</td></tr></table>
    ${report.financial.income.byCategory.some((c) => c.male || c.female) ? `<h2>Student income by gender</h2><table>
      <thead><tr><th>Category</th><th class="num">Male</th><th class="num">Female</th><th class="num">Unclassified</th></tr></thead>
      ${report.financial.income.byCategory.filter((c) => c.male || c.female).map((c) => `<tr><td>${c.category.replace(/_/g, ' ')}</td><td class="num">${money(c.male)}</td><td class="num">${money(c.female)}</td><td class="num">${money(c.unclassified)}</td></tr>`).join('')}
    </table>` : ''}
    <h2>Expenses by category</h2>
    <table>${rows(report.financial.expense.byCategory)}<tr class="total"><td>Total</td><td class="num">${money(report.financial.expense.total)}</td></tr></table>
    ${Object.values(report.financial.transfers).some((v) => Number(v) !== 0) ? `<h2>Capital &amp; transfers</h2><table>
      ${report.financial.transfers.capitalInjection ? `<tr><td>Capital injected</td><td class="num">${money(report.financial.transfers.capitalInjection)}</td></tr>` : ''}
      ${report.financial.transfers.profitDistribution ? `<tr><td>Profit distributions</td><td class="num">${money(report.financial.transfers.profitDistribution)}</td></tr>` : ''}
      ${report.financial.transfers.budgetCharged ? `<tr><td>Budget funded</td><td class="num">${money(report.financial.transfers.budgetCharged)}</td></tr>` : ''}
      ${report.financial.transfers.budgetReturned ? `<tr><td>Budget returned to treasury</td><td class="num">${money(report.financial.transfers.budgetReturned)}</td></tr>` : ''}
      ${report.financial.transfers.budgetTransferred ? `<tr><td>Budget reassigned between lines</td><td class="num">${money(report.financial.transfers.budgetTransferred)}</td></tr>` : ''}
      ${report.financial.transfers.savingTransferred ? `<tr><td>Savings transferred</td><td class="num">${money(report.financial.transfers.savingTransferred)}</td></tr>` : ''}
    </table>` : ''}
    <h2>Operational summary</h2>
    <table>
      <thead><tr><th>Metric</th><th class="num">Male</th><th class="num">Female</th><th class="num">Total</th></tr></thead>
      ${([
        ['New students', report.operational.newStudents],
        ['Active students', report.operational.activeStudents],
        ['Registrations', report.operational.registrations],
        ['Visitors', report.operational.visitors],
        ['Placement completed', report.operational.placementCompleted],
        ['Certificates issued', report.operational.certificatesIssued],
      ] as Array<[string, { male: number; female: number; total: number }]>).map(([label, g]) =>
        `<tr><td>${label}</td><td class="num">${g.male}</td><td class="num">${g.female}</td><td class="num"><b>${g.total}</b></td></tr>`).join('')}
      <tr><td>Exams conducted</td><td class="num" colspan="3">${report.operational.examsConducted}</td></tr>
      <tr><td>Books sold</td><td class="num" colspan="3">${report.operational.booksSold.count} (${money(report.operational.booksSold.total)})</td></tr>
    </table>
    <p class="muted" style="margin-top:24px;font-size:10px">Figures are computed from the authoritative database at generation time. Report ID ${m.reportId}.</p>
  `;

  const opened = openPrintDocument({
    title: `Report ${m.reportId}`,
    footerNote: `${m.type} · ${m.periodLabel} · Report ID ${m.reportId}`,
    signatures: [{ role: 'Prepared by', name: m.generatedBy.name }, { role: 'Reviewed by' }],
    bodyHtml,
  });
  if (!opened) {
    window.alert('The print window was blocked by the browser. Allow pop-ups for this site and try again.');
  }
}

export default function OperationsReportView() {
  const [period, setPeriod] = useState<Period>('month');
  const [gender, setGender] = useState<Gender>('all');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [report, setReport] = useState<OperationsReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const query: Record<string, string | undefined> = { period, gender };
      if (period === 'range') { query.from = from; query.to = to; }
      const data = await api.get<OperationsReport>('/reports/overview', query);
      setReport(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate the report.');
    } finally {
      setLoading(false);
    }
  }, [period, gender, from, to]);

  // The operations report aggregates students, visitors and classes.
  const reportVersion = useDatasetVersion('students', 'visitors', 'classes');
  useEffect(() => {
    void (async () => { await load(); })();
  }, [load, reportVersion]);

  const m = report?.meta;

  return (
    <div className="space-y-6 text-start font-sans">
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <h2 className="text-xl font-extrabold text-slate-900">Operations &amp; Financial Report</h2>
          <p className={text.hint}>Server-computed from the authoritative database; printable and traceable.</p>
        </div>
        <div className="flex flex-wrap items-end gap-2">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase block">Period</label>
            <select value={period} onChange={(e) => setPeriod(e.target.value as Period)} className={inputCls}>
              <option value="today">Today</option>
              <option value="month">This month</option>
              <option value="year">This year</option>
              <option value="range">Custom range</option>
            </select>
          </div>
          {period === 'range' && (
            <>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase block">From</label>
                <ShamsiDateInput value={from} onChange={setFrom} />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase block">To</label>
                <ShamsiDateInput value={to} onChange={setTo} />
              </div>
            </>
          )}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-400 uppercase block">Gender</label>
            <select value={gender} onChange={(e) => setGender(e.target.value as Gender)} className={inputCls}>
              <option value="all">Male + Female</option>
              <option value="male">Male only</option>
              <option value="female">Female only</option>
            </select>
          </div>
          <button type="button" onClick={() => void load()} disabled={loading} className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-[11px] font-bold cursor-pointer disabled:opacity-50 flex items-center gap-1.5">
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} /> Generate
          </button>
          {report && (
            <button type="button" onClick={() => printableReport(report)} className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-[11px] font-bold cursor-pointer flex items-center gap-1.5">
              <Printer className="w-3.5 h-3.5" /> Print
            </button>
          )}
        </div>
      </div>

      {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-xs font-semibold text-rose-700">{error}</div>}
      {loading && !report && <div className="py-16 text-center text-xs text-slate-400 font-semibold">Generating report…</div>}
      {report && m && (
        <div className="space-y-5">
          {/* Header */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm">
            <div className="text-[11px] font-black text-rose-700 tracking-wide">{BRAND_NAME}</div>
            <div className="text-sm font-extrabold text-slate-900 mt-0.5">Operations &amp; Financial Report — {m.periodLabel}</div>
            <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-1 text-[11px] text-slate-500">
              <span>Report ID: <b className="text-slate-800 font-mono">{m.reportId}</b></span>
              <span>Period: <b className="text-slate-800">{m.from} → {m.to}</b></span>
              <span>Scope: <b className="text-slate-800">{m.filters.scope}{m.filters.branchName ? ` · ${m.filters.branchName}` : ''}{m.filters.campusName ? ` · ${m.filters.campusName}` : ''}</b></span>
              <span>Gender filter: <b className="text-slate-800">{m.filters.gender}</b></span>
              <span>Generated by: <b className="text-slate-800">{m.generatedBy.name}</b> ({m.position})</span>
              <span>Timestamp: <b className="text-slate-800">{formatJalaliDateTime(m.generatedAt)}</b></span>
            </div>
          </div>

          {/* Financial */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400 flex items-center gap-1"><Wallet className="w-3.5 h-3.5" /> Operating income</div>
              <div className="text-xl font-extrabold font-mono text-emerald-700 mt-1">{formatAFN(report.financial.income.total)}</div>
              <div className="text-[10px] text-slate-400 mt-0.5">{report.financial.collectedPayments.count} payments collected ({formatAFN(report.financial.collectedPayments.total)})</div>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400 flex items-center gap-1"><TrendingDown className="w-3.5 h-3.5" /> Operating expenses</div>
              <div className="text-xl font-extrabold font-mono text-rose-700 mt-1">{formatAFN(report.financial.expense.total)}</div>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400 flex items-center gap-1"><TrendingUp className="w-3.5 h-3.5" /> Net</div>
              <div className={`text-xl font-extrabold font-mono mt-1 ${report.financial.net >= 0 ? 'text-emerald-700' : 'text-rose-700'}`}>{report.financial.net >= 0 ? '+' : ''}{formatAFN(report.financial.net)}</div>
            </div>
          </div>

          {/* Discounts, outstanding balances, previous-period comparison (server-computed) */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400">Discounts granted</div>
              <div className="text-xl font-extrabold font-mono text-slate-900 mt-1">{formatAFN(report.financial.discounts.invoiceDiscounts + report.financial.discounts.registrationDiscounts)}</div>
              <div className="text-[10px] text-slate-400 mt-0.5">Invoices {formatAFN(report.financial.discounts.invoiceDiscounts)} · Registrations {formatAFN(report.financial.discounts.registrationDiscounts)}</div>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400">Receivable (as at today)</div>
              <div className="text-xl font-extrabold font-mono text-amber-700 mt-1">{formatAFN(report.financial.outstanding.total)}</div>
              <div className="text-[10px] text-slate-400 mt-0.5">
                Tuition {formatAFN(report.financial.outstanding.tuition)} · Other {formatAFN(report.financial.outstanding.nonTuition)}
                {' · '}{report.financial.outstanding.openInvoices} open invoices
              </div>
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
              <div className="text-[10px] uppercase font-bold text-slate-400">vs previous period ({report.financial.previous.from} → {report.financial.previous.to})</div>
              {(() => {
                const prev = report.financial.previous;
                const dIncome = report.financial.income.total - prev.income;
                const dExpense = report.financial.expense.total - prev.expense;
                const pct = (n: number) => (prev.income !== 0 || prev.expense !== 0) ? `${n >= 0 ? '+' : ''}${n.toFixed(1)}%` : '—';
                const pctIncome = prev.income !== 0 ? ((report.financial.income.total - prev.income) / Math.abs(prev.income)) * 100 : 0;
                const pctExpense = prev.expense !== 0 ? ((report.financial.expense.total - prev.expense) / Math.abs(prev.expense)) * 100 : 0;
                void pct; void dIncome; void dExpense;
                return (
                  <div className="space-y-1 text-[11px]">
                    <div className="flex justify-between"><span className="text-slate-500">Income</span><span className={`font-mono font-bold ${dIncome >= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>{formatAFN(dIncome)} ({pctIncome >= 0 ? '+' : ''}{pctIncome.toFixed(1)}%)</span></div>
                    <div className="flex justify-between"><span className="text-slate-500">Expense</span><span className={`font-mono font-bold ${dExpense <= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>{formatAFN(dExpense)} ({pctExpense >= 0 ? '+' : ''}{pctExpense.toFixed(1)}%)</span></div>
                    <div className="flex justify-between border-t border-slate-100 pt-1"><span className="text-slate-500 font-bold">Net</span><span className="font-mono font-extrabold">{formatAFN(report.financial.net - prev.net)}</span></div>
                  </div>
                );
              })()}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm">
              <h3 className="text-xs font-extrabold text-slate-900 mb-2">Income by category</h3>
              <div className="space-y-1.5">
                {report.financial.income.byCategory.length === 0 && <p className="text-[11px] text-slate-400 italic">No income in this period.</p>}
                {report.financial.income.byCategory.map((c) => (
                  <div key={c.category} className="flex justify-between text-[11px] border-b border-slate-50 pb-1.5">
                    <span className="capitalize text-slate-600 font-semibold">{c.category.replace(/_/g, ' ')}</span>
                    <span className="font-mono font-bold text-emerald-700">{formatAFN(c.total)}</span>
                  </div>
                ))}
              </div>
              {Object.values(report.financial.transfers).some((v) => Number(v) !== 0) && (
                <div className="mt-3 pt-2 border-t border-slate-100 text-[10px] text-slate-400">
                  Capital injected: <b>{formatAFN(report.financial.transfers.capitalInjection)}</b> · Budget funded: <b>{formatAFN(report.financial.transfers.budgetCharged)}</b> · Budget returned: <b>{formatAFN(report.financial.transfers.budgetReturned)}</b> · Budget reassigned: <b>{formatAFN(report.financial.transfers.budgetTransferred)}</b> · Savings transferred: <b>{formatAFN(report.financial.transfers.savingTransferred)}</b> · Profit distributions: <b>{formatAFN(report.financial.transfers.profitDistribution)}</b>
                </div>
              )}
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm">
              <h3 className="text-xs font-extrabold text-slate-900 mb-2">Student income by gender</h3>
              <div className="space-y-1.5">
                {report.financial.income.byCategory.filter((c) => c.male || c.female).length === 0 && <p className="text-[11px] text-slate-400 italic">No student-linked income in this period.</p>}
                {report.financial.income.byCategory.filter((c) => c.male || c.female).map((c) => (
                  <div key={c.category} className="grid grid-cols-4 text-[11px] border-b border-slate-50 pb-1.5">
                    <span className="capitalize text-slate-600 font-semibold col-span-1">{c.category.replace(/_/g, ' ')}</span>
                    <span className="font-mono text-slate-700">M {formatAFN(c.male)}</span>
                    <span className="font-mono text-slate-700">F {formatAFN(c.female)}</span>
                    <span className="font-mono text-slate-400">{c.unclassified > 0 ? `${formatAFN(c.unclassified)} n/c` : ''}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Operational */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm">
            <h3 className="text-xs font-extrabold text-slate-900 mb-3 flex items-center gap-1.5"><Users className="w-4 h-4 text-indigo-600" /> Operational summary</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {[
                { icon: <UserPlus className="w-3.5 h-3.5" />, label: 'New students', g: report.operational.newStudents },
                { icon: <Users className="w-3.5 h-3.5" />, label: 'Active students', g: report.operational.activeStudents },
                { icon: <GraduationCap className="w-3.5 h-3.5" />, label: 'Registrations', g: report.operational.registrations },
                { icon: <Users className="w-3.5 h-3.5" />, label: 'Visitors', g: report.operational.visitors },
                { icon: <FileText className="w-3.5 h-3.5" />, label: 'Placement completed', g: report.operational.placementCompleted },
                { icon: <FileText className="w-3.5 h-3.5" />, label: 'Certificates issued', g: report.operational.certificatesIssued },
              ].map((item) => (
                <div key={item.label} className="rounded-xl bg-slate-50 border border-slate-100 p-3">
                  <div className="text-[10px] text-slate-400 font-bold uppercase flex items-center gap-1">{item.icon} {item.label}</div>
                  <div className="text-base font-extrabold text-slate-900 mt-1">{item.g.total}</div>
                  <div className="text-[10px] text-slate-500">♂ {item.g.male} · ♀ {item.g.female}</div>
                </div>
              ))}
              <div className="rounded-xl bg-slate-50 border border-slate-100 p-3">
                <div className="text-[10px] text-slate-400 font-bold uppercase flex items-center gap-1"><FileText className="w-3.5 h-3.5" /> Exams conducted</div>
                <div className="text-base font-extrabold text-slate-900 mt-1">{report.operational.examsConducted}</div>
              </div>
              <div className="rounded-xl bg-slate-50 border border-slate-100 p-3">
                <div className="text-[10px] text-slate-400 font-bold uppercase flex items-center gap-1"><BookOpen className="w-3.5 h-3.5" /> Books sold</div>
                <div className="text-base font-extrabold text-slate-900 mt-1">{report.operational.booksSold.count}</div>
                <div className="text-[10px] text-slate-500">{formatAFN(report.operational.booksSold.total)}</div>
              </div>
            </div>
            {report.operational.booksByTitle?.length > 0 && (
              <div className="mt-3 border-t border-slate-100 pt-3">
                <h4 className="text-[11px] font-extrabold text-slate-700 mb-2">Books by title</h4>
                <div className="space-y-1.5">
                  {report.operational.booksByTitle.map((b) => (
                    <div key={b.title} className="flex justify-between text-[11px] border-b border-slate-50 pb-1">
                      <span className="text-slate-600 font-semibold">{b.title} <span className="text-slate-400">× {b.quantity}</span></span>
                      <span className="font-mono font-bold text-emerald-700">{formatAFN(b.net)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Balances */}
          <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm flex flex-wrap gap-6 text-xs">
            <span>Main account: <b className="font-mono">{formatAFN(report.financial.balances.main)}</b></span>
            <span>Savings reserve: <b className="font-mono text-emerald-700">{formatAFN(report.financial.balances.saving)}</b></span>
            <span>Budget allocated: <b className="font-mono">{formatAFN(report.financial.balances.budgetAllocated)}</b></span>
            <span>Budget remaining: <b className="font-mono text-indigo-700">{formatAFN(report.financial.balances.budgetRemaining)}</b></span>
            <span className="text-slate-400">Daily saving: {m.settings.dailySavingPercent}%</span>
          </div>
        </div>
      )}
    </div>
  );
}
