/**
 * Report export.
 * ============================================================================
 * Serializes a report that has ALREADY been run. It takes a `ReportResult` —
 * the exact object the API returns — and never touches the database.
 *
 * That is the whole design. §77 requires the database, the API, the screen, the
 * printed copy and the export to agree, and the reliable way to guarantee it is
 * to make disagreement unrepresentable: there is one execution, and every
 * surface renders its output. An export that re-queried, or that a browser
 * assembled from the rendered table, could differ from what the operator was
 * looking at — silently, and in a file that then travels outside the system.
 *
 * The file carries its own provenance: report, period, the resolved Gregorian
 * span, the branch scope and the generation time. A spreadsheet that has been
 * emailed twice is otherwise impossible to place, and a reader cannot tell a
 * branch report from an organization-wide one by looking at the numbers.
 */
import { toCsv } from '../../utils/csv.js';
import type { ReportResult } from './report-engine.js';

/** How a metric's unit is spelled in an export, so a reader can interpret it. */
const UNIT_LABEL: Record<ReportResult['metrics'][number]['unit'], string> = {
  afn: 'AFN',
  count: 'count',
  percent: '%',
  days: 'days',
};

export interface ReportExportContext {
  /** ISO timestamp the export was produced at. */
  generatedAt: string;
  /** Who asked for it, for the audit trail inside the file itself. */
  generatedBy?: string;
}

/**
 * The CSV filename for a report run.
 *
 * Includes the period key rather than only the period name, so two exports of
 * "month" taken in different months do not overwrite each other in a downloads
 * folder.
 */
export function reportExportFilename(result: ReportResult): string {
  return `${result.id}-${result.boundaries.periodKey}.csv`;
}

/**
 * Renders a report result as CSV.
 *
 * Values are emitted as raw numbers, not formatted strings: a spreadsheet must
 * receive a number it can sum. Formatting (thousands separators, the AFN
 * suffix, Persian digits) is a presentation concern and belongs to the screen
 * and the printed copy, which is why the unit travels in its own column
 * instead of being baked into the value.
 */
export function reportToCsv(result: ReportResult, context: ReportExportContext): string {
  const scopeLabel = result.scope.isAll
    ? 'All branches'
    : (result.scope.branchId ?? 'Unscoped');

  const provenance: (readonly unknown[])[] = [
    ['Report', result.title],
    ['Purpose', result.purpose],
    ['Category', result.category],
    ['Period', result.period],
    ['Period key', result.boundaries.periodKey],
    ['From', result.boundaries.from],
    ['To', result.boundaries.to],
    ['Branch scope', scopeLabel],
    ['Generated at', context.generatedAt],
    ...(context.generatedBy ? [['Generated by', context.generatedBy] as const] : []),
    [],
  ];

  const metricRows = result.metrics.map((m) => [m.id, m.label, m.value, UNIT_LABEL[m.unit], m.note]);

  // The provenance block is written as two-column rows above the table. A
  // single document keeps the numbers and the span they cover together; a
  // separate "metadata" file gets lost.
  const head = toCsv(['Field', 'Value'], provenance);
  const body = toCsv(['Metric', 'Label', 'Value', 'Unit', 'Definition'], metricRows);
  return `${head}\r\n${body}\r\n`;
}
